### ISSUE TITLE
Invitation to the Functional Programming Slack Team link is broken

### ISSUE THREAD

**Issue by marciofrayze** [giraffe-fsharp/giraffe-website#1]
The link (in "Please use this link") at `https://giraffe.wiki/#contact-and-slack-channel` is broken.

It's pointing to `https://fpchat-invite.herokuapp.com`, which is down.

Btw, nice project! I might use it in my next task :)

**Comment by 64J0** [comment]
Thanks for the heads-up. This Slack channel is not maintained anymore, I think.

**Comment by marciofrayze** [comment]
Thanks for the reply.

Looks like the link was fixed somehow. Closing this issue.
